openapi: 3.1.0
info:
  title: Demo Google Sheets API
  version: "1.0.0"
  description: API para leer datos de Google Sheets usando una API key.

servers:
  - url: https://sheets.googleapis.com/v4

paths:
  /spreadsheets/{spreadsheetId}/values/{range}:
    get:
      operationId: getSheetValues
      summary: Leer rango de Google Sheets
      description: Retorna los valores de un rango específico de una hoja de cálculo de Google Sheets.
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
        - name: range
          in: path
          required: true
          schema:
            type: string
        - name: key
          in: query
          required: true
          schema:
            type: string
          description: Tu API key de Google Cloud
      responses:
        '200':
          description: Valores leídos exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SheetValuesResponse'

components:
  schemas:
    SheetValuesResponse:
      type: object
      properties:
        range:
          type: string
        majorDimension:
          type: string
        values:
          type: array
          items:
            type: array
            items:
              type: string
